logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: '*'

spring:
  application:
    name: blocker
  jackson:
    property-naming-strategy: SNAKE_CASE
  reactor:
    context-propagation: AUTO