version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    ports:
      - '8082:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm --verbose

  consul_server:
    image: hashicorp/consul:1.21
    volumes:
      - /consul/data
    ports:
      - "8500:8500" # HTTP API and UI
      - "8600:8600/tcp" # DNS TCP
      - "8600:8600/udp" # DNS UDP
    command: "agent -server -bootstrap-expect=1 -client=0.0.0.0 -dev"

  gateway:
    build:
      target: gateway
    depends_on:
      - consul_server
    ports:
      - '8080:8080'
    environment:
      - spring.cloud.consul.host=consul_server
      - spring.cloud.consul.port=8500
      - spring.cloud.consul.config.import-check.enabled=false

  ui:
    build:
      target: ui
    depends_on:
      - consul_server
    restart: unless-stopped
    environment:
      - spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/master
      - spring.cloud.consul.host=consul_server
      - spring.cloud.consul.port=8500
      - spring.cloud.consul.config.import-check.enabled=false
      - USER_CLIENT_BASE_URL=http://gateway/accounts/
      - TRANSFER_CLIENT_BASE_URL=http://gateway/transfer/
      - BLOCKER_CLIENT_BASE_URL=http://gateway/blocker/

  transfer:
    build:
      target: transfer
    environment:
      - spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/master
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/master
      - spring.cloud.consul.host=consul_server
      - spring.cloud.consul.port=8500
      - spring.cloud.consul.config.import-check.enabled=false
      - USER_CLIENT_BASE_URL=http://gateway/accounts/
      - EXCHANGE_CLIENT_BASE_URL=http://gateway/exchange/
      - BLOCKER_CLIENT_BASE_URL=http://gateway/blocker/
    depends_on:
      - consul_server
      - keycloak
    restart: unless-stopped

  exchange_generator:
    build:
      target: exchange_generator
    environment:
      - spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/master
      - spring.cloud.consul.host=consul_server
      - spring.cloud.consul.port=8500
      - spring.cloud.consul.config.import-check.enabled=false
      - EXCHANGE_CLIENT_BASE_URL=http://gateway/exchange/
    depends_on:
      - consul_server
      - keycloak
      - exchange
    restart: unless-stopped

  accounts_cache:
    image: redis:8-alpine

  accounts:
    build:
      target: accounts
    environment:
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/master
      - spring.cloud.consul.host=consul_server
      - spring.cloud.consul.port=8500
      - spring.cloud.consul.config.import-check.enabled=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accounts_db:5432/accounts
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - spring.data.redis.host=accounts_cache
      - spring.data.redis.port=6379
      - spring.cache.redis.time-to-live=PT5S
    depends_on:
      - consul_server
      - accounts_cache
      - accounts_db
      - keycloak

  accounts_db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  exchange_cache:
    image: redis:8-alpine

  exchange:
    build:
      target: exchange
    environment:
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/master
      - spring.cloud.consul.host=consul_server
      - spring.cloud.consul.port=8500
      - spring.cloud.consul.config.import-check.enabled=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://exchange_db:5432/exchange
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - spring.data.redis.host=exchange_cache
      - spring.data.redis.port=6379
      - spring.cache.redis.time-to-live=PT5S
    depends_on:
      - consul_server
      - exchange_cache
      - exchange_db
      - keycloak

  exchange_db:
    image: postgres:17-alpine
    ports:
      - '5442:5432'
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  blocker:
    build:
      target: blocker
    restart: unless-stopped
    environment:
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/master
      - spring.cloud.consul.host=consul_server
      - spring.cloud.consul.port=8500
      - spring.cloud.consul.config.import-check.enabled=false
    depends_on:
      - consul_server
      - keycloak