apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer