logging:
  level:
    root: DEBUG

management:
  endpoints.web.exposure.include: health
  # Позволяет видеть детальную информацию о состоянии
  endpoint.health.show-details: always

spring:
  application:
    name: accounts
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: 'classpath:/db/changelog/liquibase/main.xml'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    consul:
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию