logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: health
  # Позволяет видеть детальную информацию о состоянии
  endpoint.health.show-details: always

notifications-client:
  base-url: ${NOTIFICATIONS_CLIENT_BASE_URL}

spring:
  application:
    name: accounts
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: 'classpath:/db/changelog/liquibase/main.xml'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak-rest-client: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: rest-client
            client-secret: 8lHWta5ggYFsrJN5eUEKn3j8YmZqLbSl
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
  jackson:
    property-naming-strategy: SNAKE_CASE