logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: health
  # Позволяет видеть детальную информацию о состоянии
  endpoint.health.show-details: always

spring:
  application:
    name: accounts
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: 'classpath:/db/changelog/liquibase/main.xml'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    admin:
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.add.type.headers: false