kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  spring.security.oauth2.resourceserver.jwt.issuer-uri: {{ tpl .Values.configmap.data.RESOURCE_SERVER_JWT_ISSUER_URI . | quote }}