kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  spring.security.oauth2.resourceserver.jwt.issuer-uri: {{ tpl .Values.configmap.data.RESOURCE_SERVER_JWT_ISSUER_URI . | quote }}
  spring.kafka.bootstrap-servers: {{ tpl .Values.configmap.data.KAFKA_BOOTSTRAP_SERVERS . | quote }}
  management.zipkin.tracing.endpoint: {{ tpl .Values.configmap.data.ZIPKIN_TRACING_ENDPOINT . | quote }}
  management.tracing.sampling.probability: {{ .Values.configmap.data.ZIPKIN_SAMPLING_PROBABILITY | quote }}