appName: exchange-generator

port: 8080

configmap:
  name: exchange-generator
  data:
    KAFKA_BOOTSTRAP_SERVERS: "kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
    ZIPKIN_TRACING_ENDPOINT: "http://zipkin.{{ .Release.Namespace }}.svc.cluster.local:9411/api/v2/spans"
    ZIPKIN_SAMPLING_PROBABILITY: 1

image:
  name: exchange_generator
  tag: latest