logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: health

user-client:
  base-url: ${USER_CLIENT_BASE_URL}

spring:
  application:
    name: ui
  cloud:
    consul:
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию