logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: health

user-client:
  base-url: ${USER_CLIENT_BASE_URL}

transfer-client:
  base-url: ${TRANSFER_CLIENT_BASE_URL}

cash-client:
  base-url: ${CASH_CLIENT_BASE_URL}

exchange-client:
  base-url: ${EXCHANGE_CLIENT_BASE_URL}

spring:
  application:
    name: ui
  security:
    oauth2:
      client:
        registration:
          keycloak-rest-client: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: rest-client
            client-secret: 8lHWta5ggYFsrJN5eUEKn3j8YmZqLbSl
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
  jackson:
    property-naming-strategy: SNAKE_CASE