appName: notifications

port: 8080

namespace: default

configmap:
  name: notifications
  data:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak.{{ .Values.namespace }}.svc.cluster.local:8080/realms/master"

image:
  name: notifications
  tag: latest