input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["accounts-logs", "blocker-logs", "cash-logs", "exchange-logs", "exchange-generator-logs", "notifications-logs", "transfer-logs", "ui-logs"]
    group_id => "bankapp-group"
    decorate_events => true # Add Kafka @metadata to events (e.g., topic, partition, offset)
  }
}
filter {
  grok {
    match => { "message" => "%{TIME:time} %{LOGLEVEL:log-level}%{SPACE}: %{GREEDYDATA:msg}\n" }
  }
  mutate {
    copy => { "[@metadata][kafka][topic]" => "[source]" }
  }
  mutate {
    remove_field => [ "username", "event", "message", "@version", "@metadata" ]
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bankapp-%{[source]}-%{+YYYY.MM.dd}"
    retry_on_conflict => 3
    action => "index"
  }
}