apiVersion: v2
name: exchange
description: Helm chart for exchange microservice
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "22.0.7"
    repository: "oci://registry-1.docker.io/bitnamicharts"

  - name: postgresql
    version: "16.7.27"
    repository: "oci://registry-1.docker.io/bitnamicharts"
