apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 9092
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP