logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: health

spring:
  application:
    name: notifications
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    listener.ack-mode: manual
    consumer:
      group-id: notifications-kafka-client
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.value.default.type: com.example.bankapp.notifications.model.EmailNotificationDto
      auto-offset-reset: earliest
      enable-auto-commit: false