logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: health
  # Позволяет видеть детальную информацию о состоянии
  endpoint.health.show-details: always

spring:
  application:
    name: exchange
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: 'classpath:/db/changelog/liquibase/main.xml'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    listener.ack-mode: manual
    consumer:
      group-id: exchange-kafka-client
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.value.default.type: com.example.bankapp.exchange.model.UpdateRateRequestDto
      auto-offset-reset: latest
      enable-auto-commit: false