logging:
  level:
    root: WARN

management:
  endpoints.web.exposure.include: health
  # Позволяет видеть детальную информацию о состоянии
  endpoint.health.show-details: always

spring:
  application:
    name: exchange
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: 'classpath:/db/changelog/liquibase/main.xml'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE